### ISSUE TITLE
Error when save file

### ISSUE THREAD

**Issue by bzy-debug** [nobody-famous/alive#127]
Thanks for your great plugin. But I encounter some errors.
When editing in VScode, everytime I save a file, it triggers an error.

```
[Error - 11:24:43] Request textDocument/rangeFormatting failed.
Error: The received response has neither a result nor an error property.
    at handleInvalidMessage (/Users/bzy/.vscode/extensions/rheller.alive-0.3.19/node_modules/vscode-jsonrpc/lib/common/connection.js:579:40)
    at processMessageQueue (/Users/bzy/.vscode/extensions/rheller.alive-0.3.19/node_modules/vscode-jsonrpc/lib/common/connection.js:295:17)
    at Immediate.<anonymous> (/Users/bzy/.vscode/extensions/rheller.alive-0.3.19/node_modules/vscode-jsonrpc/lib/common/connection.js:276:13)
    at processImmediate (node:internal/timers:466:21)
```

System: macOS 12.6.2
VScode version: 
1.74.1
1ad8d514439d5077d2b0b7ee64d2ce82a9308e5a
arm64
sbcl version: SBCL 2.2.11

**Comment by bzy-debug** [comment]
This problem seems related to the formatter. When I stop using the lisp formatter provided by alive, errors are gone.

**Comment by nobody-famous** [comment]
There does seem to be some issues with the formatting code. I haven't seen the same error you have, but I'm seeing issues that might be causing it. I'm looking into it.

**Comment by nobody-famous** [comment]
Ok, I was able to recreate it. Hopefully it won't take too long to fix now that I see what's wrong.

**Comment by nobody-famous** [comment]
Fixed
