### ISSUE TITLE
Error when running "Alive: System Skeleton" in Dev Container

### ISSUE THREAD

**Issue by cantpitch** [nobody-famous/alive#69]
Probably not a super-common use case, but when running lisp in a container (i.e. "Remote-Containers: Open Folder in Container..." with a Dockerfile based on `clfoundation/sbcl:2.1.5`) the "Alive: System Skeleton" throws the error:

```
[Error: Folder not empty 
at Object.<anonymous> (/root/.vscode-server/extensions/rheller.alive-0.2.5/out/src/vscode/SystemSkeleton.js:21:19) 
at Generator.next (<anonymous>) 
at fulfilled (/root/.vscode-server/extensions/rheller.alive-0.2.5/out/src/vscode/SystemSkeleton.js:5:58) 
at runMicrotasks (<anonymous>) 
at processTicksAndRejections (internal/process/task_queues.js:93:5)]
```

The `Dockerfile` is just:
```
FROM clfoundation/sbcl:2.1.5
```

**Comment by nobody-famous** [comment]
Looks like it needs to be smarter than "all or nothing" on checking for files. The fact that the Dockerfile is there is stopping it. I'll look into a smarter way to do it. I might just disable that check.

**Comment by nobody-famous** [comment]
I uploaded a new version with that check disabled. It should work. If you run it twice, it overwrites the files it puts down.

**Comment by cantpitch** [comment]
It works now! I appreciate the quick turn-around. Thanks!
